[0.576s] Invoking command in '/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/src/control_package': AMENT_PREFIX_PATH=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/install/control_package:${AMENT_PREFIX_PATH} PYTEST_ADDOPTS=--tb=short --junit-xml=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/control_package/pytest.xml --junit-prefix=control_package -o cache_dir=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/control_package/.pytest_cache PYTHONPATH=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/install/control_package/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 -m pytest
[2.408s] [1m============================= test session starts ==============================[0m
[2.408s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[2.408s] cachedir: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/control_package/.pytest_cache
[2.408s] rootdir: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/src/control_package
[2.408s] plugins: ament-xmllint-0.14.1, ament-copyright-0.14.1, ament-flake8-0.14.1, launch-testing-2.0.2, ament-pep257-0.14.1, launch-testing-ros-0.24.0, ament-lint-0.14.1, colcon-core-0.12.1, cov-3.0.0
[2.408s] [1mcollecting ... [0m[1m
[2.408s] collected 3 items                                                              [0m
[2.408s] 
[2.408s] test/test_copyright.py [33ms[0m[32m                                                 [ 33%][0m
[2.408s] test/test_flake8.py [31mF[0m[31m                                                    [ 66%][0m
[2.408s] test/test_pep257.py [32m.[0m[31m                                                    [100%][0m
[2.408s] 
[2.408s] =================================== FAILURES ===================================
[2.408s] [31m[1m_________________________________ test_flake8 __________________________________[0m
[2.408s] [1m[31mtest/test_flake8.py[0m:23: in test_flake8
[2.408s]     [94massert[39;49;00m rc == [94m0[39;49;00m, \
[2.408s] [1m[31mE   AssertionError: Found 12 code style errors / warnings:[0m
[2.408s] [1m[31mE     ./control_package/control_node.py:4:1: F401 'random' imported but unused[0m
[2.408s] [1m[31mE     ./control_package/control_node.py:9:22: E231 missing whitespace after ','[0m
[2.408s] [1m[31mE     ./control_package/control_node.py:11:1: W293 blank line contains whitespace[0m
[2.408s] [1m[31mE     ./control_package/control_node.py:22:9: E265 block comment should start with '# '[0m
[2.409s] [1m[31mE     ./control_package/control_node.py:66:1: E303 too many blank lines (4)[0m
[2.409s] [1m[31mE     ./control_package/control_node.py:71:60: E231 missing whitespace after ','[0m
[2.409s] [1m[31mE     ./control_package/control_node.py:72:54: E231 missing whitespace after ','[0m
[2.409s] [1m[31mE     ./control_package/control_node.py:73:50: E231 missing whitespace after ','[0m
[2.409s] [1m[31mE     ./control_package/control_node.py:79:9: E265 block comment should start with '# '[0m
[2.409s] [1m[31mE     ./control_package/control_node.py:80:9: E265 block comment should start with '# '[0m
[2.409s] [1m[31mE     ./control_package/control_node.py:81:1: W293 blank line contains whitespace[0m
[2.409s] [1m[31mE     ./control_package/control_node.py:90:11: W292 no newline at end of file[0m
[2.409s] [1m[31mE   assert 1 == 0[0m
[2.409s] ----------------------------- Captured stdout call -----------------------------
[2.409s] 
[2.409s] ./control_package/control_node.py:4:1: F401 'random' imported but unused
[2.409s] import random
[2.409s] ^
[2.409s] 
[2.409s] ./control_package/control_node.py:9:22: E231 missing whitespace after ','
[2.409s]     def __init__(self,node):
[2.409s]                      ^
[2.409s] 
[2.409s] ./control_package/control_node.py:11:1: W293 blank line contains whitespace
[2.409s]     
[2.409s] ^
[2.409s] 
[2.409s] ./control_package/control_node.py:22:9: E265 block comment should start with '# '
[2.409s]         #print("SUB:",self.parsed_sub_data)
[2.410s]         ^
[2.410s] 
[2.410s] ./control_package/control_node.py:66:1: E303 too many blank lines (4)
[2.410s] def main(args=None):
[2.410s] ^
[2.410s] 
[2.410s] ./control_package/control_node.py:71:60: E231 missing whitespace after ','
[2.410s]     control_node.init_battery_data_publisher("battery_data",1)
[2.410s]                                                            ^
[2.410s] 
[2.410s] ./control_package/control_node.py:72:54: E231 missing whitespace after ','
[2.410s]     control_node.init_mppt_data_publisher("mppt_data",1)
[2.410s]                                                      ^
[2.410s] 
[2.410s] ./control_package/control_node.py:73:50: E231 missing whitespace after ','
[2.410s]     control_node.init_mc_data_publisher("mc_data",1)
[2.410s]                                                  ^
[2.410s] 
[2.410s] ./control_package/control_node.py:79:9: E265 block comment should start with '# '
[2.410s]         #control_node.mppt_pub_data = control_node.parsed_sub_data[59:115]
[2.410s]         ^
[2.410s] 
[2.410s] ./control_package/control_node.py:80:9: E265 block comment should start with '# '
[2.410s]         #control_node.mc_pub_data = control_node.parsed_sub_data[115:123]
[2.411s]         ^
[2.411s] 
[2.411s] [33m=============================== warnings summary ===============================[0m
[2.411s] test/test_flake8.py::test_flake8
[2.411s] test/test_flake8.py::test_flake8
[2.411s]   Warning: SelectableGroups dict interface is deprecated. Use select.
[2.411s] 
[2.411s] -- Docs: https://docs.pytest.org/en/stable/warnings.html
[2.414s] ./control_package/control_node.py:81:1: W293 blank line contains whitespace
[2.414s]         
[2.414s] ^
[2.415s] 
[2.415s] ./control_package/control_node.py:90:11: W292 no newline at end of file
[2.415s]     main()          ^
[2.415s] 
[2.415s] 4     E231 missing whitespace after ','
[2.415s] 3     E265 block comment should start with '# '
[2.415s] 1     E303 too many blank lines (4)
[2.415s] 1     F401 'random' imported but unused
[2.415s] 1     W292 no newline at end of file
[2.415s] 2     W293 blank line contains whitespace
[2.415s] 
[2.415s] 6 files checked
[2.415s] 12 errors
[2.415s] 
[2.415s] 'E'-type errors: 8
[2.415s] 'F'-type errors: 1
[2.415s] 'W'-type errors: 3
[2.415s] 
[2.415s] Checked files:
[2.415s] 
[2.415s] * ./setup.py
[2.416s] * ./test/test_flake8.py
[2.416s] * ./test/test_pep257.py
[2.416s] * ./test/test_copyright.py
[2.416s] * ./control_package/__init__.py
[2.416s] * ./control_package/control_node.py
[2.416s] ----------------------------- Captured stderr call -----------------------------
[2.416s] option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
[2.416s] - generated xml file: /home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/control_package/pytest.xml -
[2.416s] =========================== short test summary info ============================
[2.416s] FAILED test/test_flake8.py::test_flake8 - AssertionError: Found 12 code style...
[2.416s] [31m============== [31m[1m1 failed[0m, [32m1 passed[0m, [33m1 skipped[0m, [33m2 warnings[0m[31m in 0.20s[0m[31m ==============[0m
[2.968s] Invoked command in '/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/src/control_package' returned '1': AMENT_PREFIX_PATH=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/install/control_package:${AMENT_PREFIX_PATH} PYTEST_ADDOPTS=--tb=short --junit-xml=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/control_package/pytest.xml --junit-prefix=control_package -o cache_dir=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/build/control_package/.pytest_cache PYTHONPATH=/home/jaay/Agnirath/Agnirath_LVS_Strategy/aarush_ros/install/control_package/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 -m pytest
